platform: wheelchair
use_lidar_odom: false
detection_linear_state_time_bias: -0.05
detection_angular_state_time_bias: 0.0
image_processing_interval: 0.5
visualize: true
vis_interval: 0.5
annotate_image: true

prompts:
  chair:
    - chair
  sofa:
    - sofa
  table:
    - table
  wall:
    - wall
    - white wall
    - blue wall
    - black wall
  cabinet:
    - white cabinet
  floor:
    - floor
  ceiling:
    - ceiling
  garbagebin:
    - garbage bin
  refrigerator:
    - silver refrigerator
  column:
    - structural column
  sign:
    - safety sign
    - caution sign
  microwave:
    - microwave
  coffeemachine:
    - coffee machine
  pottedplant:
    - small potted plant
    - plant pot
    - plant
  fireextinguisher:
    - fire extinguisher
  door:
    - door
  # television:
  #   - television
  # painting:
  #   - painting on the wall